apiVersion: apps/v1
kind: Deployment
metadata:
  name: pojoht
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pojoht
  template:
    metadata:
      labels:
        app: pojoht
    spec:
      containers:
      - image: okteto.dev/pojoht:latest
        name: pojoht
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "985ddb3a-1d17-4180-9af9-4dd86d8a441c"
        - name: Vless_Path
          value: "/vl8975255"
        - name: Vmess_UUID
          value: "985ddb3a-1d17-4180-9af9-4dd86d8a441c"
        - name: Vmess_Path
          value: "/vm8698646"
        - name: Share_Path
          value: "/v2link"
